### ISSUE TITLE
CURL-OPENSSL_3 not found

### ISSUE THREAD

**Issue by DrProfSgtMrJ** [jaagr/polybar#1192]
I recently upgraded to Ubuntu 18.04 and when I tried to run polybar again I got the issue:
polybar: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by polybar)

I tried to build it again and got:

Scanning dependencies of target xpp
[  1%] Linking CXX static library libxpp.a
Traceback (most recent call last):
  File "/home/jade/.config/polybar/polybar/lib/xpp/generators/cpp_client.py", line 3163, in <module>
    from xcbgen.state import Module
  File "/usr/lib/python2.7/dist-packages/xcbgen/state.py", line 7, in <module>
    from xcbgen import matcher
  File "/usr/lib/python2.7/dist-packages/xcbgen/matcher.py", line 12, in <module>
    from xcbgen.xtypes import *
  File "/usr/lib/python2.7/dist-packages/xcbgen/xtypes.py", line 1221, in <module>
    class EventStruct(Union):
  File "/usr/lib/python2.7/dist-packages/xcbgen/xtypes.py", line 1239, in EventStruct
    out = __main__.output['eventstruct']
KeyError: 'eventstruct'
lib/xpp/CMakeFiles/xpp.dir/build.make:68: recipe for target 'lib/xpp/libxpp.a' failed
make[2]: *** [lib/xpp/libxpp.a] Error 1
CMakeFiles/Makefile2:402: recipe for target 'lib/xpp/CMakeFiles/xpp.dir/all' failed
make[1]: *** [lib/xpp/CMakeFiles/xpp.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by patrick96** [comment]
Recompiling was the right move. The other issue is already known (#1090). Either compile against the latest commit, or manually update the xpp submodule to the latest commit
