### ISSUE TITLE
Failed to build package

### ISSUE THREAD

**Issue by DevGrohl** [jaagr/polybar#1252]
I'm having problems building the package in Archlinux since a few weeks ago.
I don't usually post issues so let me know if more info it's needed.

> Traceback (most recent call last):
  File "/home/mike/.cache/pacaur/polybar/src/polybar/lib/xpp/generators/cpp_client.py", line 3163, in <module>
    from xcbgen.state import Module
  File "/usr/lib/python3.6/site-packages/xcbgen/state.py", line 7, in <module>
    from xcbgen import matcher
  File "/usr/lib/python3.6/site-packages/xcbgen/matcher.py", line 12, in <module>
    from xcbgen.xtypes import *
  File "/usr/lib/python3.6/site-packages/xcbgen/xtypes.py", line 1221, in <module>
    class EventStruct(Union):
  File "/usr/lib/python3.6/site-packages/xcbgen/xtypes.py", line 1239, in EventStruct
    out = __main__.output['eventstruct']
KeyError: 'eventstruct'
make[2]: *** [lib/xpp/CMakeFiles/xpp.dir/build.make:70: lib/xpp/libxpp.a] Error 1
make[1]: *** [CMakeFiles/Makefile2:403: lib/xpp/CMakeFiles/xpp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
:: failed to build polybar package(s)

**Comment by patrick96** [comment]
See [Known-Issues](https://github.com/jaagr/polybar/wiki/Known-Issues)

On Arch it is recommended to build `polybar` from the AUR, which doesn't have that issue
