### ISSUE TITLE
[module/volume] Not Working & Build Error

### ISSUE THREAD

**Issue by Dentrax** [jaagr/polybar#1287]
Hey,

Even though I set everything up correctly, volume module does not work. Also I tried `internal/alsa` and `internal/pulseaudio` too.

Configuration volume module in polybar config: `modules-right = volume`

`mpd` was installed

```
mpd --version
Music Player Daemon 0.20.20
```

Output: `polybar --version` 

```
polybar 3.1.0-128-g77d36b9

Features: +alsa +curl -i3 -mpd +network +pulseaudio
```

Output: `amixer scontrols`

```
Simple mixer control 'IEC958',0
Simple mixer control 'IEC958',1
Simple mixer control 'IEC958',2
Simple mixer control 'IEC958',3
Simple mixer control 'IEC958',4
```

Output: `amixer -c 0 scontrols`

```
numid=25,iface=CARD,name='HDMI/DP,pcm=10 Jack'
numid=1,iface=CARD,name='HDMI/DP,pcm=3 Jack'
numid=7,iface=CARD,name='HDMI/DP,pcm=7 Jack'
numid=13,iface=CARD,name='HDMI/DP,pcm=8 Jack'
numid=19,iface=CARD,name='HDMI/DP,pcm=9 Jack'
numid=2,iface=MIXER,name='IEC958 Playback Con Mask'
numid=8,iface=MIXER,name='IEC958 Playback Con Mask',index=1
numid=14,iface=MIXER,name='IEC958 Playback Con Mask',index=2
numid=20,iface=MIXER,name='IEC958 Playback Con Mask',index=3
numid=26,iface=MIXER,name='IEC958 Playback Con Mask',index=4
numid=3,iface=MIXER,name='IEC958 Playback Pro Mask'
numid=9,iface=MIXER,name='IEC958 Playback Pro Mask',index=1
numid=15,iface=MIXER,name='IEC958 Playback Pro Mask',index=2
numid=21,iface=MIXER,name='IEC958 Playback Pro Mask',index=3
numid=27,iface=MIXER,name='IEC958 Playback Pro Mask',index=4
numid=4,iface=MIXER,name='IEC958 Playback Default'
numid=10,iface=MIXER,name='IEC958 Playback Default',index=1
numid=16,iface=MIXER,name='IEC958 Playback Default',index=2
numid=22,iface=MIXER,name='IEC958 Playback Default',index=3
numid=28,iface=MIXER,name='IEC958 Playback Default',index=4
numid=5,iface=MIXER,name='IEC958 Playback Switch'
numid=11,iface=MIXER,name='IEC958 Playback Switch',index=1
numid=17,iface=MIXER,name='IEC958 Playback Switch',index=2
numid=23,iface=MIXER,name='IEC958 Playback Switch',index=3
numid=29,iface=MIXER,name='IEC958 Playback Switch',index=4
numid=6,iface=PCM,name='ELD',device=3
numid=31,iface=PCM,name='Playback Channel Map',device=3
numid=12,iface=PCM,name='ELD',device=7
numid=32,iface=PCM,name='Playback Channel Map',device=7
numid=18,iface=PCM,name='ELD',device=8
numid=33,iface=PCM,name='Playback Channel Map',device=8
numid=24,iface=PCM,name='ELD',device=9
numid=34,iface=PCM,name='Playback Channel Map',device=9
numid=30,iface=PCM,name='ELD',device=10
numid=35,iface=PCM,name='Playback Channel Map',device=10
```

My Module/Volume Configuration:

```
[module/volume]
type = internal/volume

master-soundcard = default
speaker-soundcard = default
headphone-soundcard = default

master-mixer = Master
speaker-mixer = Speaker
headphone-mixer = Headphone

headphone-id = 9

mapped = true

format-volume = <ramp-volume> <label-volume>
label-muted =   muted
label-muted-foreground = #66

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-3 = 

ramp-headphones-0 = 
ramp-headphones-1 = 
```
Output: `polybar --log=info top`

```
[dentrax@arch etc]$ polybar --log=info top
* Loading config: /home/dentrax/.config/polybar/config
* Loaded monitor eDP-1 (1920x1080+0+0)
* Bar geometry: 1920x34+0+0
error: Disabling module "mpd" (reason: No built-in support for 'internal/mpd')
error: Disabling module "volume" (reason: Could not connect pulseaudio context.)
error: Disabling module "wired-network" (reason: Invalid network interface "net0")
* Starting application
* Starting module/powermenu
* Starting module/cpu
* Starting module/memory
* Starting module/backlight
* Starting module/wireless-network
* Starting module/battery
* Starting module/date
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=9)
* Configured DPI = 96x96
* Loaded font "NotoSans-Regular:size=8" (name=Noto Sans, offset=-1, file=/usr/share/fonts/noto/NotoSans-Regular.ttf)
* Loaded font "MaterialIcons:size=10" (name=Material Icons, offset=0, file=/usr/share/fonts/TTF/MaterialIcons-Regular.ttf)
* Loaded font "Termsynu:size=8:antialias=false" (name=DejaVu Sans, offset=-2, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
* Loaded font "FontAwesome:size=10" (name=FontAwesome, offset=0, file=/usr/share/fonts/OTF/FontAwesome.otf)
* Bar window: 0x2000001
* Disabling tray manager (reason: missing `tray-position`)
* module/powermenu: Rebuilding cache
* module/cpu: Rebuilding cache
* module/memory: Rebuilding cache
* module/backlight: Rebuilding cache
* module/wireless-network: Rebuilding cache
* module/battery: Rebuilding cache
* module/date: Rebuilding cache
* Redrawing bar window
* module/battery: Polling values (inotify fallback)
* module/memory: Rebuilding cache
* module/cpu: Rebuilding cache
* Redrawing bar window
* module/wireless-network: Rebuilding cache
warn: Termination signal received, shutting down...
* module/powermenu: Stopping
* Deconstruction of module/powermenu took 0 ms.
* module/cpu: Stopping
* Deconstruction of module/cpu took 0 ms.
* module/memory: Stopping
* Deconstruction of module/memory took 0 ms.
* module/backlight: Stopping
* Deconstruction of module/backlight took 444 ms.
* module/wireless-network: Stopping
* Deconstruction of module/wireless-network took 0 ms.
* module/battery: Stopping
* Deconstruction of module/battery took 138 ms.
* module/date: Stopping
* Deconstruction of module/date took 0 ms.
* Waiting for spawned processes to end
* Reached end of application...
```

Also I have this problem while I am building the source from build.sh.

```
[dentrax@arch polybar]$ sudo ./build.sh -f
[sudo] password for dentrax: 
** Fetching submodules
** Removing existing build dir (-f)
** Setting build options
** Include support for "internal/i3" (requires i3) ------------------- [Y/n]: Y
** Include support for "internal/volume" (requires alsalib) ---------- [Y/n]: Y
** Include support for "internal/network" (requires wireless_tools) -- [Y/n]: Y
** Include support for "internal/mpd" (requires libmpdclient) -------- [Y/n]: Y
** Include support for "internal/github" (requires libcurl) ---------- [Y/n]: Y
** Build "polybar-msg" used to send ipc messages --------------------- [Y/n]: Y
** Using compiler: clang++/clang
** Executing cmake command
-- The C compiler identification is Clang 6.0.0
Y-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type specified; using RelWithDebInfo
-- Using supported compiler Clang-6.0.0
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.4.2") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Checking for module 'cairo-fc'
--   Found cairo-fc, version 1.15.12
-- Checking for module 'alsa'
--   Found alsa, version 1.1.6
-- Checking for module 'libcurl'
--   Found libcurl, version 7.60.0
-- Checking for module 'libmpdclient'
--   Found libmpdclient, version 2.14
-- Found Libiw: /usr/lib/libiw.so  
-- Checking for module 'xcb-xkb'
--   Found xcb-xkb, version 1.13
-- Checking for module 'xcb-randr'
--   Found xcb-randr, version 1.13
-- Checking for module 'xcb-randr>=1.12'
--   Found xcb-randr, version 1.13
-- Checking for module 'xcb-xrm'
--   Found xcb-xrm, version 1.3
-- Checking for module 'xcb-cursor'
--   Found xcb-cursor, version 0.1.3
--  Build:
--    Type: RelWithDebInfo
--    CC: /usr/bin/clang  -O2 -g -DNDEBUG
--    CXX: /usr/bin/clang++  -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors -Wno-error=parentheses-equality -O2 -g -DNDEBUG
--    LD: /usr/bin/ld  
--  Targets:
-- [X]   polybar-msg
-- [ ]   testsuite
--  Module support:
-- [X]   alsa
-- [X]   curl
-- [X]   i3
-- [X]   mpd
-- [X]   network
--  X extensions:
-- [X]   xcb-randr
-- [X]   xcb-randr (monitor support)
-- [ ]   xcb-render
-- [ ]   xcb-damage
-- [ ]   xcb-sync
-- [ ]   xcb-composite
-- [X]   xcb-xkb
-- [X]   xcb-xrm
-- [X]   xcb-cursor
-- Font not found: fixed:pixelsize=10
-- Font not found: unifont:fontformat=truetype
-- Font not found: siji:pixelsize=10
-- Checking for module 'xcb-proto'
--   Found xcb-proto, version 1.13
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.15", minimum required is "2.7") 
-- XCB[XCB]: Found component XCB
-- Found XCB_XCB: /usr/lib/libxcb.so  
-- XCB[ICCCM]: Found component ICCCM
-- Found XCB_ICCCM: /usr/lib/libxcb-icccm.so  
-- XCB[EWMH]: Found component EWMH
-- Found XCB_EWMH: /usr/lib/libxcb-ewmh.so  
-- XCB[UTIL]: Found component UTIL
-- Found XCB_UTIL: /usr/lib/libxcb-util.so  
-- XCB[IMAGE]: Found component IMAGE
-- Found XCB_IMAGE: /usr/lib/libxcb-image.so  
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so  
-- Searching for xcbgen with python2
-- Searching for xcbgen with python3
-- Found xcbgen in /usr/lib/python3.6/site-packages
-- XCB[RANDR]: Found component RANDR
-- Found XCB_RANDR: /usr/lib/libxcb-randr.so  
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so;/usr/lib/libxcb-randr.so  
-- XCB[XKB]: Found component XKB
-- Found XCB_XKB: /usr/lib/libxcb-xkb.so  
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so;/usr/lib/libxcb-randr.so;/usr/lib/libxcb-xkb.so  
-- xpp: including xcb proto randr.xml
-- xpp: including xcb proto xkb.xml
-- xpp: including xcb proto xproto.xml
-- Checking for module 'jsoncpp>=1.7.7'
--   Found jsoncpp, version 1.8.4
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dentrax/Downloads/polybar/build
** Building project
Scanning dependencies of target xpp
[  1%] Linking CXX static library libxpp.a
Traceback (most recent call last):
  File "/home/dentrax/Downloads/polybar/lib/xpp/generators/cpp_client.py", line 3163, in <module>
    from xcbgen.state import Module
  File "/usr/lib/python3.6/site-packages/xcbgen/state.py", line 7, in <module>
    from xcbgen import matcher
  File "/usr/lib/python3.6/site-packages/xcbgen/matcher.py", line 12, in <module>
    from xcbgen.xtypes import *
  File "/usr/lib/python3.6/site-packages/xcbgen/xtypes.py", line 1221, in <module>
    class EventStruct(Union):
  File "/usr/lib/python3.6/site-packages/xcbgen/xtypes.py", line 1239, in EventStruct
    out = __main__.output['eventstruct']
KeyError: 'eventstruct'
make[2]: *** [lib/xpp/CMakeFiles/xpp.dir/build.make:70: lib/xpp/libxpp.a] Error 1
make[1]: *** [CMakeFiles/Makefile2:403: lib/xpp/CMakeFiles/xpp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
** Failed to build project
```

**Comment by patrick96** [comment]
How are you running polybar, when you can't build it? For the build issue, see [Known-Issues](https://github.com/jaagr/polybar/wiki/Known-Issues).

Your polybar wasn't compiled with mpd support, that's why the mpd module doesn't work. Was libmpdclient installed when you built polybar?

As for the volume module, the log you posted doesn't match with the volume module you posted. The volume module that you posted, is an alsa module, while the volume module error in your log could only have been produced by the pulseaudio module. Please post your volume module that doesn't work together with the polybar output when you run that config.

**Comment by Dentrax** [comment]
I'm running Polybar through Openbox's `autostart` file. I added this code: `polybar -q top &`

Thank you I fixed the `eventstruct` bug. But when I run the `sudo make install`, it is not working. Build output here: https://paste.ee/p/uYzV6

Also libmpdclient was installed already.

My volume output for your last question:

```
[dentrax@arch polybar]$ polybar --log=info top
* Loading config: /home/dentrax/.config/polybar/config
* Loaded monitor eDP-1 (1920x1080+0+0)
* Bar geometry: 1920x34+0+0
error: Disabling module "mpd" (reason: No built-in support for 'internal/mpd')
warn: internal/volume is deprecated, use internal/alsa instead
error: Disabling module "volume" (reason: Cannot find simple element)
...
...
...
```

**Comment by patrick96** [comment]
Hmm, the polybar you have just newly built, does it have mpd support enabled?

In your volume module, you probably have the wrong master, speaker and/or headphone mixers defined. See the [Wiki](https://github.com/jaagr/polybar/wiki/Module:-volume) for how to set those values.

**Comment by Dentrax** [comment]
@patrick96 Yes, It was enabled now. My `polybar --version` output:

```
polybar 3.1.0-153-gd43a4a8-git

Features: +alsa +curl +i3 +mpd +network +pulseaudio +xkeyboard
```
For your second you said, I can't figure out what to write to default places. The wiki is not fully disclosed I think.

`/proc/asound/cards` output:

```
 0 [HDMI           ]: HDA-Intel - HDA Intel HDMI
                      HDA Intel HDMI at 0xf7a14000 irq 40
 1 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xf7a10000 irq 31
```

`amixer scontrols | sed -nr "s/.*'([[:alnum:]]+)'.*/\1/p"` output:

```
IEC958
IEC958
IEC958
IEC958
IEC958
```

**Comment by patrick96** [comment]
Seems like your actual sound card is number `1` and not `0`. You will need to use `amixer -c 1 scontrols` to get the name of your mixers.

**Comment by Dentrax** [comment]
`amixer -c 1 scontrols` output:

```
Simple mixer control 'Master',0
Simple mixer control 'Headphone',0
Simple mixer control 'Speaker',0
Simple mixer control 'Bass Speaker',0
Simple mixer control 'Mic',0
Simple mixer control 'Mic Boost',0
Simple mixer control 'IEC958',0
Simple mixer control 'IEC958 Default PCM',0
Simple mixer control 'Capture',0
Simple mixer control 'Auto-Mute Mode',0
Simple mixer control 'Loopback Mixing',0
```

How should I use these outputs? My mixer configurations looks like good. All the other modules are running properly, but that sounds a little-difficult, or I couldn't. :)

**Comment by patrick96** [comment]
Did you set `master-soundcard = hw:1`?

**Comment by Dentrax** [comment]
@patrick96 Yes, But I have still this error: 
`error: Disabling module "volume" (reason: Cannot find simple element)`

Config:

```
[module/volume]
type = internal/alsa

master-soundcard = hw:1
speaker-soundcard = default
headphone-soundcard = default

master-mixer = Master
speaker-mixer = Speaker
headphone-mixer = Headphone

sink = alsa_output.pci-0000_12_00.3.analog-stereo
use-ui-max = true

headphone-id = 9

mapped = true

format-volume = <ramp-volume> <label-volume>
label-muted =   muted
label-muted-foreground = #66

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-3 = 

ramp-headphones-0 = 
ramp-headphones-1 = 
```

**Comment by patrick96** [comment]
I think, you also have to set `speaker-soundcard` and `headphone-soundcard` to `hw:1`

**Comment by Dentrax** [comment]
Thank you! Headphone icon appears now. But headset is not plugged in. How do I make it appear speaker icon by default?

**Comment by Dentrax** [comment]
Thank you so much! Everything working fine now. :)
