### ISSUE TITLE
xcbgen detection fails

### ISSUE THREAD

**Issue by stkw0** [jaagr/polybar#1520]
## Build Process
When building polybar from Gentoo it can't detect xcbgen although xcb-proto (with python3 only) is installed. When I install xcb-proto with also python2 it builds correctly.

This may be related with issue #1496 . 

## Build Log
```cmake -C /tmp/portage/x11-misc/polybar-3.2.1/work/polybar-3.2.1_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_ALSA=yes -DENABLE_CURL=no -DENABLE_I3=no -DBUILD_IPC_MSG=no -DENABLE_MPD=no -DENABLE_NETWORK=no -DENABLE_PULSEAUDIO=yes -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/tmp/portage/x11-misc/polybar-3.2.1/work/polybar-3.2.1_build/gentoo_toolchain.cmake  /tmp/portage/x11-misc/polybar-3.2.1/work/polybar-3.2.1
loading initial cache file /tmp/portage/x11-misc/polybar-3.2.1/work/polybar-3.2.1_build/gentoo_common_config.cmake
-- Trying to enable ccache
-- Using compiler cache /usr/bin/ccache
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using supported compiler GNU-8.2.0
-- Found PkgConfig: x86_64-pc-linux-gnu-pkg-config (found version "0.29.2")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Checking for module 'cairo-fc'
--   Found cairo-fc, version 1.16.0
-- Checking for module 'alsa'
--   Found alsa, version 1.1.7
-- Checking for module 'libpulse'
--   Found libpulse, version 12.2
-- Checking for module 'xcb-xkb'
--   Found xcb-xkb, version 1.13.1
-- Checking for module 'xcb-randr'
--   Found xcb-randr, version 1.13.1
-- Checking for module 'xcb-randr>=1.12'
--   Found xcb-randr, version 1.13.1
-- Checking for module 'xcb-xrm'
--   Found xcb-xrm, version 1.3
-- Checking for module 'xcb-cursor'
--   Found xcb-cursor, version 0.1.3
--  Build:
--    Type: Gentoo
--    CC: /usr/bin/x86_64-pc-linux-gnu-gcc -O2 -pipe -march=native -mtune=native -O2 -flto
--    CXX: /usr/bin/x86_64-pc-linux-gnu-g++ -O2 -pipe -march=native -mtune=native -O2 -flto -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
--    LD: /usr/bin/ld -Wl,-O1 -Wl,--as-needed -flto
--  Targets:
-- [ ]   polybar-msg
-- [ ]   testsuite
--  Module support:
-- [X]   alsa (1.1.7)
-- [ ]   curl
-- [ ]   i3
-- [ ]   mpd
-- [ ]   network
-- [X]   pulseaudio (12.2)
-- [X]   xkeyboard (1.13.1)
--  X extensions:
-- [X]   xcb-randr (1.13.1)
-- [X]   xcb-randr (monitor support) (1.13.1)
-- [ ]   xcb-render
-- [ ]   xcb-damage
-- [ ]   xcb-sync
-- [ ]   xcb-composite
-- [X]   xcb-xkb (1.13.1)
-- [X]   xcb-xrm (1.3)
-- [X]   xcb-cursor (0.1.3)
--  Log options:
-- [X]   Trace logging
-- Font not found: fixed:pixelsize=10
-- Found font: unifont:fontformat=truetype
-- Font not found: siji:pixelsize=10
-- Checking for module 'xcb-proto'
--   Found xcb-proto, version 1.13
-- Found PythonInterp: /tmp/portage/x11-misc/polybar-3.2.1/temp/python2.7/bin/python (found suitable version "2.7.15", minimum required is "2.7")
-- XCB[XCB]: Found component XCB
-- Found XCB_XCB: /usr/lib/libxcb.so
-- XCB[ICCCM]: Found component ICCCM
-- Found XCB_ICCCM: /usr/lib/libxcb-icccm.so
-- XCB[EWMH]: Found component EWMH
-- Found XCB_EWMH: /usr/lib/libxcb-ewmh.so
-- XCB[UTIL]: Found component UTIL
-- Found XCB_UTIL: /usr/lib/libxcb-util.so
-- XCB[IMAGE]: Found component IMAGE
-- Found XCB_IMAGE: /usr/lib/libxcb-image.so
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-image.so
-- Searching for xcbgen with python2
-- Searching for xcbgen with python3
-- Searching for xcbgen with python
CMake Error at lib/xpp/CMakeLists.txt:55 (message):
  Missing required python module: xcbgen```

**Comment by patrick96** [comment]
Can you apply the following patch to `lib/xpp/CMakeLists.txt` and post the output of cmake again. If this is the same issue as #1496 then this should give us some more info.
```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3a87cc4..87eb218 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -40,7 +40,8 @@ foreach(CURRENT_EXECUTABLE python2 python3 python)
     "import re,xcbgen;print(re.compile('/xcbgen/__init__.py.*').sub('',xcbgen.__file__))"
     RESULT_VARIABLE _xcbgen_status
     OUTPUT_VARIABLE _xcbgen_location
-    ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
+    OUTPUT_STRIP_TRAILING_WHITESPACE)
+  message(STATUS "status: " ${_xcbgen_status)
 
   # When a shell script returns successfully its return code is 0
   if(_xcbgen_status EQUAL 0)
```

Also, are you using something like anaconda?
Can you also please post the output of the following three commands:
```bash
python2 -c "import re,xcbgen;print(re.compile('/xcbgen/__init__.py.*').sub('',xcbgen.__file__))" && echo $?
```

```bash
python3 -c "import re,xcbgen;print(re.compile('/xcbgen/__init__.py.*').sub('',xcbgen.__file__))" && echo $?
```

```bash
python -c "import re,xcbgen;print(re.compile('/xcbgen/__init__.py.*').sub('',xcbgen.__file__))" && echo $?
```

**Comment by stkw0** [comment]
I created a small Dockerfile to reproduce it. It basically disables the python2 support on XCB and then emerges the dependencies.
```
FROM gentoo/stage3-amd64

RUN emerge-webrsync
RUN mkdir -p /etc/portage/package.use; echo "x11-base/xcb-proto -python_targets_python2_7" > /etc/portage/package.use/polybar-test
RUN emerge -qo polybar --autounmask-continue --jobs 2
# RUN emerge -v polybar --autounmask-continue
```

The output of the 3 commands are the next

```bash
f6dc9e864030 / # python2 -c "import re,xcbgen;print(re.compile('/xcbgen/__init__.py.*').sub('',xcbgen.__file__))" && ec
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named xcbgen
f6dc9e864030 / # python3 -c "import re,xcbgen;print(re.compile('/xcbgen/__init__.py.*').sub('',xcbgen.__file__))" && ec
/usr/lib64/python3.6/site-packages
0
f6dc9e864030 / # python -c "import re,xcbgen;print(re.compile('/xcbgen/__init__.py.*').sub('',xcbgen.__file__))" && ech
/usr/lib64/python3.6/site-packages
0
f6dc9e864030 / #
```

**Comment by stkw0** [comment]
Seems that the problem was of the distro, removing the ERROR_QUIET it outputs
```-- Searching for xcbgen with python3
: python_wrapper_setup: python3 is not supported by python2.7 (PYTHON_COMPAT)``` for python3 and ```Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named xcbgen``` for python and python2

**Comment by stkw0** [comment]
Also, why it checks for python3 support? In the README it says that it requires python2

**Comment by patrick96** [comment]
Weird that within cmake you can't run `python3` but in the terminal you can. But yeah, seems to be an issue with the distro or your setup. Maybe extending the `PYTHON_COMPAT` variable in the ebuild with python 3.7 could help:
```bash
PYTHON_COMPAT=( python2_7 python3_6 )
```

`python2` support is always needed because we use it to generate the headers in the `xpp` submodule. But we also require whatever python version xcbgen uses, otherwise we wouldn't be able to figure out the location of xcbgen. For example on my system, the xcbgen python files are for python3, so we need `python3` to find them. But this can be configured during packaging, as you have done.
