### ISSUE TITLE
Build errors in AUR package

### ISSUE THREAD

**Issue by gatlinnewhouse** [jaagr/polybar#564]
```zsh
-- Build files have been written to: /home/deleuze/.cache/pacaur/polybar/src/polybar/build
[  1%] Linking CXX static library libxpp.a
Traceback (most recent call last):
  File "/home/deleuze/.cache/pacaur/polybar/src/polybar/lib/xpp/generators/cpp_client.py", line 3163, in <module>
    from xcbgen.state import Module
  File "/usr/lib/python3.6/site-packages/xcbgen/state.py", line 7, in <module>
    from xcbgen import matcher
  File "/usr/lib/python3.6/site-packages/xcbgen/matcher.py", line 12, in <module>
    from xcbgen.xtypes import *
  File "/usr/lib/python3.6/site-packages/xcbgen/xtypes.py", line 1201, in <module>
    class EventStruct(Union):
  File "/usr/lib/python3.6/site-packages/xcbgen/xtypes.py", line 1219, in EventStruct
    out = __main__.output['eventstruct']
KeyError: 'eventstruct'
make[2]: *** [lib/xpp/CMakeFiles/xpp.dir/build.make:70: lib/xpp/libxpp.a] Error 1
make[1]: *** [CMakeFiles/Makefile2:385: lib/xpp/CMakeFiles/xpp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
:: failed to build polybar package(s)
```

**Comment by Tmplt** [comment]
I can't reproduce this with either `polybar` or `polybar-git` without pacaur. Try cloning the AUR repo directly.

**Comment by gatlinnewhouse** [comment]
I tried cloning the AUR repo directly and using makepkg but I got the same error message.

**Comment by gatlinnewhouse** [comment]
Installed `xcb-proto`, removed `xcb-proto-git`, and installed `xpyb-git`. Now things seem to be working
