### ISSUE TITLE
Self referenced colours caused a segfault

### ISSUE THREAD

**Issue by spurgelaurels** [jaagr/polybar#783]
Definitely not a normal thing to do, but I accidentally copied colours from the bottom bar to the top bar like this:  
```
[bar/top]
background = ${bar/top.background}
foreground = ${bar/top.foreground}
```
  

Definitely not urgent, as this was user-error, but segfaults are bad.  

On Arch linux:  
```
polybar 3.0.5-70-g5b7d7b8

Features: +alsa +curl +i3 +mpd +network
```

**Comment by patrick96** [comment]
I was able to reproduce this.
[Here](https://gist.github.com/patrick96/d7a35109d370e4ff8244fd3613f3b7f1) is the stacktrace (**warning:** it's huge)

I think these lines are the important ones:
```
#0  0x0000555555937898 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > > >::_S_value (__x=<error reading variable: Cannot access memory at address 0x7fffff7feff8>) at /usr/include/c++/7.2.0/bits/stl_tree.h:755
...
#5  0x000055555591e3d0 in polybar::v3_0_5_70_g5b7d7b8_git::config::get<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (this=0x555555e28b00, section="bar/example", key="background") at /home/patrick96/Projects/github.com/patrick96/polybar/include/components/config.hpp:75
#6  0x000055555592bbf5 in polybar::v3_0_5_70_g5b7d7b8_git::config::dereference_local<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (this=0x555555e28b00, section="bar/example", key="background", current_section="bar/example") at /home/patrick96/Projects/github.com/patrick96/polybar/include/components/config.hpp:247
#7  0x0000555555923506 in polybar::v3_0_5_70_g5b7d7b8_git::config::dereference<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (this=0x555555e28b00, section="bar/example", key="background", var="${bar/example.background}", fallback="${bar/example.background}") at /home/patrick96/Projects/github.com/patrick96/polybar/include/components/config.hpp:221
#8  0x000055555591e609 in polybar::v3_0_5_70_g5b7d7b8_git::config::get<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (this=0x555555e28b00, section="bar/example", key="background") at /home/patrick96/Projects/github.com/patrick96/polybar/include/components/config.hpp:79
```

This seems to be the relevant part of the first one:
```
... <error reading variable: Cannot access memory at address 0x7fffff7feff8> ...
```
and for the almost the rest of the stacktrace, these three lines are repeating themselves:
```
(this=0x555555e28b00, section="bar/example", key="background", current_section="bar/example") at /home/patrick96/Projects/github.com/patrick96/polybar/include/components/config.hpp:247
(this=0x555555e28b00, section="bar/example", key="background", var="${bar/example.background}", fallback="${bar/example.background}") at /home/patrick96/Projects/github.com/patrick96/polybar/include/components/config.hpp:221
(this=0x555555e28b00, section="bar/example", key="background") at /home/patrick96/Projects/github.com/patrick96/polybar/include/components/config.hpp:79
```

So this is an issue with infinite recursion, which makes sense because polybar is trying to resolve the background variable, for which it has to resolve the background variable and so on.

I'll take a stab at solving this.
