### ISSUE TITLE
Error launching

### ISSUE THREAD

**Issue by slacky90** [jaagr/polybar#816]
In Slackware 14.2, i3-gaps wm.  I ofter get the following error when starting polybar. I managed to do a dirty fix running polybar in an infinite loop till it stays running.

terminate called after throwing an instance of 'xpp::x::error::match'
what():  XCB_MATCH (8)

**Comment by patrick96** [comment]
Does this happen with any config or just with a specific one?
What is the output of `polybar -vvv`?

**Comment by slacky90** [comment]
It happens running "polybar example".
This is the output of polybar -vvv:
polybar 3.0.5

Features: +alsa +curl +i3 -mpd +network

X extensions: +randr (-monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -O2 -fPIC -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags:

**Comment by patrick96** [comment]
Can you run polybar with the `-l info` argument and post the whole output here as well.

**Comment by slacky90** [comment]
Sure.

* Loaded /home/eric/.config/polybar/config
warn: No monitor specified, using "eDP1"
* Loaded monitor eDP1 (1366x768+0+0)
* Bar geometry: 1366x35+0+0
error: Disabling module "bspwm" (reason: Could not find socket: /tmp/bspwm_0_0-socket)
* Starting application
* Starting module/i3
* Starting module/filesystem
* Starting module/xbacklight
* Starting module/volume
* Starting module/xkeyboard
* Starting module/memory
* Starting module/cpu
* Starting module/wlan
* Starting module/eth
* Starting module/battery
* Starting module/temperature
* Starting module/date
* Starting module/powermenu
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=15)
* Configured DPI = 96x96
* Loaded font "fixed:pixelsize=10" (name=Fixed, offset=1, file=/usr/share/fonts/misc/6x10-ISO8859-1.pcf.gz)
* Loaded font "unifont:fontformat=truetype:size=8:antialias=false" (name=DejaVu Sans, offset=0, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
* Loaded font "siji:pixelsize=10" (name=DejaVu Sans, offset=1, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
* Bar window: 0x0e00003
* Activating tray manager
* Tray window: 0x0e0000a
terminate called after throwing an instance of 'xpp::x::error::match'
  what():  XCB_MATCH (8)
Abortado

**Comment by patrick96** [comment]
Can you disable the tray and see if the error still occurs.

**Comment by slacky90** [comment]
Yup. Commenting out the lines 

;tray-position = right
;tray-padding = 2

In ~/.config/polybar/config seems to have fixed the problem. Now it stays running. 
Thank you vey much!

**Comment by jaagr** [comment]
@slacky90 would you be able to compile polybar manually in debug mode to enable more detailed logging?

**Comment by slacky90** [comment]
Sure. The bar has been running fine though. Can you give me some instructions to compile it in
debug mode?

**Comment by patrick96** [comment]
Instead of running `cmake ..` you will have to run `cmake -DCMAKE_BUILD_TYPE=Debug ..` in order to compile in debug mode. The rest of the compilation steps are the same as before.

**Comment by patrick96** [comment]
Closing due to inactivity

**Comment by bemagri** [comment]
I also have the same problem on slackware 14.2
Whenever override-redirect = false the bar fails to run if the tray is enabled.

Output below:

$ polybar example -c .config/polybar/config -l info      
* Loaded .config/polybar/config
warn: No monitor specified, using "LVDS"
* Loaded monitor LVDS (1366x768+0+0)
* Bar geometry: 1366x23+0+0
error: module/mpd: Connection refused
* Starting application
* Starting module/i3
* Starting module/xwindow
* Starting module/mpd
* Starting module/volume
* Starting module/memory
* Starting module/cpu
* Starting module/battery
* Starting module/temperature
* Starting module/date
* Starting module/powermenu
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=12)
* Configured DPI = 96x96
* Loaded font "fixed:size=10" (name=Fixed, offset=0, file=/usr/share/fonts/misc/6x10-ISO8859-1.pcf.gz)
* Loaded font "unifont:fontformat=truetype:size=6:heavy" (name=Unifont, offset=-2, file=/usr/share/fonts/TTF/unifont-8.0.01.ttf)
* Loaded font "FontAwesome:size=9" (name=FontAwesome, offset=0, file=/usr/share/fonts/OTF/fontawesome-webfont.ttf)
* Bar window: 0x2200001
* Activating tray manager
* Tray window: 0x2200005
terminate called after throwing an instance of 'xpp::x::error::match'
  what():  XCB_MATCH (8)
[1]    2825 abort      polybar example -c .config/polybar/config -l info

**Comment by NBonaparte** [comment]
Could you run it with gdb and post the backtrace here?

**Comment by bemagri** [comment]
Sorry for the late response.
I compiled polybar 3.2.1 in debug mode and ran it with gdb.

(gdb) run example -c ~/.config/polybar/config
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /usr/local/bin/polybar example -c ~/.config/polybar/config
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffec28c700 (LWP 4143)]
warn: No monitor specified, using "LVDS"
warn: internal/volume is deprecated, use internal/alsa instead
[New Thread 0x7fffe7885700 (LWP 4146)]
warn: module/temperature: The token `%temperature%` is deprecated, use `%temperature-c%` instead.
[New Thread 0x7fffe7084700 (LWP 4147)]
[New Thread 0x7fffe6883700 (LWP 4149)]
[New Thread 0x7fffe6082700 (LWP 4150)]
[Thread 0x7fffe6883700 (LWP 4149) exited]
[New Thread 0x7fffe5881700 (LWP 4151)]
[New Thread 0x7fffe5080700 (LWP 4152)]
[New Thread 0x7fffe487f700 (LWP 4153)]
[New Thread 0x7fffdbffe700 (LWP 4154)]
[New Thread 0x7fffdb7fd700 (LWP 4155)]
[New Thread 0x7fffdaffc700 (LWP 4156)]
[New Thread 0x7fffda7fb700 (LWP 4157)]
[New Thread 0x7fffd9ffa700 (LWP 4158)]
[Thread 0x7fffda7fb700 (LWP 4157) exited]
error: tray: Failed to put tray above 0x2600001 in the stack (XCB_MATCH (8))
[New Thread 0x7fffd8c40700 (LWP 4159)]
[Thread 0x7fffd8c40700 (LWP 4159) exited]


Curiously, the error shows up but the bar keeps running without any apparent problems. When I compiled without debug mode the bar would not even initialize with this config.

(gdb) bt
#0  0x00007ffff43a3083 in select () from /lib64/libc.so.6
#1  0x0000000000a37341 in polybar::v3_2_1::controller::read_events (this=0xdcecc0) at /home/bernardo/Downloads/polybar/polybar-3.2.1/src/components/controller.cpp:273
#2  0x0000000000a36970 in polybar::v3_2_1::controller::run (this=0xdcecc0, writeback=false, snapshot_dst=...)
    at /home/user/Downloads/polybar/polybar-3.2.1/src/components/controller.cpp:194
#3  0x00000000008dd7bd in main (argc=4, argv=0x7fffffffe088) at /home/user/Downloads/polybar/polybar-3.2.1/src/main.cpp:143

**Comment by NBonaparte** [comment]
The error isn't supposed to stop the bar, so it's not really related.

So it only fails to run in release mode? Could you get the backtrace for that?
