### ISSUE TITLE
xpp/proto build error on openSUSE tumbleweed

### ISSUE THREAD

**Issue by yobson** [jaagr/polybar#973]
Hello

When I try to build polybar, I get this error. I have tried playing around with different dependencies and versions of polybar, but it just will not go away.

Error:

```
[  1%] Generating ../../../lib/xpp/include/xpp/proto/x.hpp
Traceback (most recent call last):
  File "/home/james/mysuseconfig/polybar/lib/xpp/generators/cpp_client.py", line 3163, in <module>
    from xcbgen.state import Module
  File "/usr/lib/python3.6/site-packages/xcbgen/state.py", line 7, in <module>
    from xcbgen import matcher
  File "/usr/lib/python3.6/site-packages/xcbgen/matcher.py", line 12, in <module>
    from xcbgen.xtypes import *
  File "/usr/lib/python3.6/site-packages/xcbgen/xtypes.py", line 1201, in <module>
    class EventStruct(Union):
  File "/usr/lib/python3.6/site-packages/xcbgen/xtypes.py", line 1219, in EventStruct
    out = __main__.output['eventstruct']
KeyError: 'eventstruct'
make[2]: *** [lib/xpp/CMakeFiles/xpp.dir/build.make:70: ../lib/xpp/include/xpp/proto/x.hpp] Error 1
make[2]: *** Deleting file '../lib/xpp/include/xpp/proto/x.hpp'
make[1]: *** [CMakeFiles/Makefile2:402: lib/xpp/CMakeFiles/xpp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

James

**Comment by edjeffreys** [comment]
I have v 3.1.0 working on my desktop, however I have the same issues when trying to build the current version on my laptop which is also running tumbleweed.

**Comment by yobson** [comment]
Thanks! I don't mind the older version :)

**Comment by patrick96** [comment]
The people in #756 and #564 had the exact same error. For them it was that their xcb-proto package was out of date. What version of xcb-proto do you have installed?

@edjeffreys does that mean that v3.0.5 builds fine on your laptop but 3.1.0 doesn't?

**Comment by edjeffreys** [comment]
@patrick96 no, I have the same error for v3.0.5 using xcb-proto-devel v1.12.

`[  1%] Generating ../../../lib/xpp/include/xpp/proto/x.hpp
Traceback (most recent call last):
  File "/home/edj/Repos/polybar/lib/xpp/generators/cpp_client.py", line 3163, in <module>
    from xcbgen.state import Module
  File "/usr/lib/python3.6/site-packages/xcbgen/state.py", line 7, in <module>
    from xcbgen import matcher
  File "/usr/lib/python3.6/site-packages/xcbgen/matcher.py", line 12, in <module>
    from xcbgen.xtypes import *
  File "/usr/lib/python3.6/site-packages/xcbgen/xtypes.py", line 1201, in <module>
    class EventStruct(Union):
  File "/usr/lib/python3.6/site-packages/xcbgen/xtypes.py", line 1219, in EventStruct
    out = __main__.output['eventstruct']
KeyError: 'eventstruct'
make[2]: *** [lib/xpp/CMakeFiles/xpp.dir/build.make:70: ../lib/xpp/include/xpp/proto/x.hpp] Error 1
make[2]: *** Deleting file '../lib/xpp/include/xpp/proto/x.hpp'
make[1]: *** [CMakeFiles/Makefile2:402: lib/xpp/CMakeFiles/xpp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`

**Comment by patrick96** [comment]
What's the output of `grep -rni "output\[" /usr/lib/python3.6/site-packages/xcbgen/`?

**Comment by edjeffreys** [comment]
```
/usr/lib/python3.6/site-packages/xcbgen/state.py:74:    open = __main__.output['open']
/usr/lib/python3.6/site-packages/xcbgen/state.py:75:    close = __main__.output['close']
/usr/lib/python3.6/site-packages/xcbgen/xtypes.py:204:    out = __main__.output['simple']
/usr/lib/python3.6/site-packages/xcbgen/xtypes.py:257:    out = __main__.output['enum']
/usr/lib/python3.6/site-packages/xcbgen/xtypes.py:957:    out = __main__.output['struct']
/usr/lib/python3.6/site-packages/xcbgen/xtypes.py:968:    out = __main__.output['union']
/usr/lib/python3.6/site-packages/xcbgen/xtypes.py:1166:    out = __main__.output['request']
/usr/lib/python3.6/site-packages/xcbgen/xtypes.py:1219:    out = __main__.output['eventstruct']
/usr/lib/python3.6/site-packages/xcbgen/xtypes.py:1308:    out = __main__.output['event']
/usr/lib/python3.6/site-packages/xcbgen/xtypes.py:1339:    out = __main__.output['error']
```

**Comment by dinotheextinct** [comment]
Exact same problem here with Tumble weed and 
Information for package xcb-proto-devel:
----------------------------------------
Repository     : openSUSE:Tumbleweed                    
Name           : xcb-proto-devel                        
Version        : 7.6_1.12-6.1                           
Arch           : x86_64                                 
Vendor         : openSUSE                               
Installed Size : 656.5 KiB                              
Installed      : Yes                                    
Status         : up-to-date                             
Source package : xcb-proto-7.6_1.12-6.1.src             
Summary        : The X11 Protocol: X Protocol C Bindings
Description    :                                        
    The XCB protocol headers for X11 development. xcb-proto provides the
    XML-XCB protocol descriptions that libxcb uses to generate the majority of
    its code and API.

**Comment by avindra** [comment]
It seems that this line:

https://cgit.freedesktop.org/xcb/proto/tree/xcbgen/xtypes.py#n1239

 is causing issues.  I suspect that this patch is breaking `xcb-proto`:

https://cgit.freedesktop.org/xcb/proto/commit/?id=4aa40fbd5e05833b72327ea37421b09dff246732

Removing it from Tumbleweed would probably fix it, but I don't know if other code depends on this yet. I would guess  not, as it appears the library is completely broken at the moment.

I've contacted the author of the patch for advice. If anyone knows how to report an issue to xcb-proto, please also do so.

**Comment by patrick96** [comment]
I think I got it. The latest xcb-proto commits use the `eventstruct` key in their `xtypes.py` file. While OpenSUSE claims to use the 1.12 version of xcb-proto, they actually manually added the new commits as patches and so SUSE also requires the `eventstruct` key. I first thought this was a version incompatibility between two non-polybar packages, but it turns out that the xpp package has to define the `eventstruct` key. I have opened a PR in https://github.com/jaagr/xpp/pull/11 that defines that key with a dummy value so that everything compiles again. Could you please try to manually apply this patch and tell us if it compiles and if polybar works properly after compiling.

**Comment by sysek** [comment]
hi @patrick96. I applied your patch with my spec file for polybar and get this errors

```
CMakeFiles/polybar.dir/utils/bspwm.cpp.o: In function `polybar::v3_1_0::bspwm_util::root_windows(polybar::v3_1_0::connection&)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/utils/bspwm.cpp:22: undefined reference to `xcb_icccm_get_wm_class'
/home/sysek/rpm/BUILD/polybar-3.1.0/src/utils/bspwm.cpp:22: undefined reference to `xcb_icccm_get_wm_class_reply'
/home/sysek/rpm/BUILD/polybar-3.1.0/src/utils/bspwm.cpp:29: undefined reference to `xcb_icccm_get_wm_class_reply_wipe'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `polybar::v3_1_0::ewmh_util::initialize()':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:17: undefined reference to `xcb_ewmh_init_atoms'
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:17: undefined reference to `xcb_ewmh_init_atoms_replies'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `polybar::v3_1_0::ewmh_util::supports(unsigned int, int)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:25: undefined reference to `xcb_ewmh_get_supported'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `xcb_ewmh_get_supported_reply':
/usr/include/xcb/xcb_ewmh.h:698: undefined reference to `xcb_ewmh_get_atoms_reply'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `polybar::v3_1_0::ewmh_util::supports(unsigned int, int)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:32: undefined reference to `xcb_ewmh_get_atoms_reply_wipe'
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:28: undefined reference to `xcb_ewmh_get_atoms_reply_wipe'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `polybar::v3_1_0::ewmh_util::get_reply_string[abi:cxx11](xcb_ewmh_get_utf8_strings_reply_t*)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:68: undefined reference to `xcb_ewmh_get_utf8_strings_reply_wipe'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `polybar::v3_1_0::ewmh_util::get_wm_name[abi:cxx11](unsigned int)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:40: undefined reference to `xcb_ewmh_get_wm_name'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `xcb_ewmh_get_wm_name_reply':
/usr/include/xcb/xcb_ewmh.h:1804: undefined reference to `xcb_ewmh_get_utf8_strings_reply'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `polybar::v3_1_0::ewmh_util::get_visible_name[abi:cxx11](unsigned int)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:49: undefined reference to `xcb_ewmh_get_wm_visible_name'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `xcb_ewmh_get_wm_visible_name_reply':
/usr/include/xcb/xcb_ewmh.h:1837: undefined reference to `xcb_ewmh_get_utf8_strings_reply'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `polybar::v3_1_0::ewmh_util::get_icon_name[abi:cxx11](unsigned int)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:58: undefined reference to `xcb_ewmh_get_wm_icon_name'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `xcb_ewmh_get_wm_icon_name_reply':
/usr/include/xcb/xcb_ewmh.h:1870: undefined reference to `xcb_ewmh_get_utf8_strings_reply'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `polybar::v3_1_0::ewmh_util::get_current_desktop(int)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:76: undefined reference to `xcb_ewmh_get_current_desktop'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `xcb_ewmh_get_current_desktop_reply':
/usr/include/xcb/xcb_ewmh.h:1223: undefined reference to `xcb_ewmh_get_cardinal_reply'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `polybar::v3_1_0::ewmh_util::get_desktop_names[abi:cxx11](int)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:96: undefined reference to `xcb_ewmh_get_desktop_names'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `xcb_ewmh_get_desktop_names_reply':
/usr/include/xcb/xcb_ewmh.h:1302: undefined reference to `xcb_ewmh_get_utf8_strings_reply'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `polybar::v3_1_0::ewmh_util::get_active_window(int)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:105: undefined reference to `xcb_ewmh_get_active_window'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `xcb_ewmh_get_active_window_reply':
/usr/include/xcb/xcb_ewmh.h:1419: undefined reference to `xcb_ewmh_get_window_reply'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `polybar::v3_1_0::ewmh_util::change_current_desktop(unsigned int)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:111: undefined reference to `xcb_ewmh_request_change_current_desktop'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `polybar::v3_1_0::ewmh_util::get_desktop_from_window(unsigned int)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:118: undefined reference to `xcb_ewmh_get_wm_desktop'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `xcb_ewmh_get_wm_desktop_reply':
/usr/include/xcb/xcb_ewmh.h:1934: undefined reference to `xcb_ewmh_get_cardinal_reply'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `polybar::v3_1_0::ewmh_util::set_wm_window_type(unsigned int, std::vector<unsigned int, std::allocator<unsigned int> >)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:124: undefined reference to `xcb_ewmh_set_wm_window_type'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `polybar::v3_1_0::ewmh_util::set_wm_state(unsigned int, std::vector<unsigned int, std::allocator<unsigned int> >)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:130: undefined reference to `xcb_ewmh_set_wm_state'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `polybar::v3_1_0::ewmh_util::get_wm_state(unsigned int)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:137: undefined reference to `xcb_ewmh_get_wm_state'
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:137: undefined reference to `xcb_ewmh_get_wm_state_reply'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `polybar::v3_1_0::ewmh_util::set_wm_pid(unsigned int)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:145: undefined reference to `xcb_ewmh_set_wm_pid'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `polybar::v3_1_0::ewmh_util::set_wm_pid(unsigned int, unsigned int)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:151: undefined reference to `xcb_ewmh_set_wm_pid'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `polybar::v3_1_0::ewmh_util::set_wm_desktop(unsigned int, unsigned int)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:157: undefined reference to `xcb_ewmh_set_wm_desktop'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `polybar::v3_1_0::ewmh_util::get_client_list(int)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:171: undefined reference to `xcb_ewmh_get_client_list'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `xcb_ewmh_get_client_list_reply':
/usr/include/xcb/xcb_ewmh.h:784: undefined reference to `xcb_ewmh_get_windows_reply'
CMakeFiles/polybar.dir/x11/ewmh.cpp.o: In function `polybar::v3_1_0::ewmh_util::get_desktop_viewports(int)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:84: undefined reference to `xcb_ewmh_get_desktop_viewport'
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/ewmh.cpp:84: undefined reference to `xcb_ewmh_get_desktop_viewport_reply'
CMakeFiles/polybar.dir/x11/icccm.cpp.o: In function `polybar::v3_1_0::icccm_util::get_reply_string[abi:cxx11](xcb_icccm_get_text_property_reply_t*)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/icccm.cpp:19: undefined reference to `xcb_icccm_get_text_property_reply_wipe'
CMakeFiles/polybar.dir/x11/icccm.cpp.o: In function `polybar::v3_1_0::icccm_util::get_wm_name[abi:cxx11](xcb_connection_t*, unsigned int)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/icccm.cpp:9: undefined reference to `xcb_icccm_get_wm_name'
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/icccm.cpp:9: undefined reference to `xcb_icccm_get_wm_name_reply'
CMakeFiles/polybar.dir/x11/icccm.cpp.o: In function `polybar::v3_1_0::icccm_util::set_wm_name(xcb_connection_t*, unsigned int, char const*, unsigned long, char const*, unsigned long)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/icccm.cpp:25: undefined reference to `xcb_icccm_set_wm_name'
CMakeFiles/polybar.dir/x11/icccm.cpp.o: In function `polybar::v3_1_0::icccm_util::get_wm_urgency(xcb_connection_t*, unsigned int)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/icccm.cpp:35: undefined reference to `xcb_icccm_get_wm_hints'
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/icccm.cpp:35: undefined reference to `xcb_icccm_get_wm_hints_reply'
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/icccm.cpp:36: undefined reference to `xcb_icccm_wm_hints_get_urgency'
CMakeFiles/polybar.dir/x11/icccm.cpp.o: In function `polybar::v3_1_0::icccm_util::set_wm_name(xcb_connection_t*, unsigned int, char const*, unsigned long, char const*, unsigned long)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/icccm.cpp:26: undefined reference to `xcb_icccm_set_wm_class'
CMakeFiles/polybar.dir/x11/icccm.cpp.o: In function `polybar::v3_1_0::icccm_util::set_wm_protocols(xcb_connection_t*, unsigned int, std::vector<unsigned int, std::allocator<unsigned int> >)':
/home/sysek/rpm/BUILD/polybar-3.1.0/src/x11/icccm.cpp:30: undefined reference to `xcb_icccm_set_wm_protocols'
collect2: error: ld returned 1 exit status
gmake[3]: *** [bin/CMakeFiles/polybar.dir/build.make:1868: bin/polybar] Error 1
gmake[3]: Leaving directory '/home/sysek/rpm/BUILD/polybar-3.1.0/build'
gmake[2]: *** [CMakeFiles/Makefile2:574: bin/CMakeFiles/polybar.dir/all] Error 2
gmake[2]: Leaving directory '/home/sysek/rpm/BUILD/polybar-3.1.0/build'
gmake[1]: *** [Makefile:133: all] Error 2
gmake[1]: Leaving directory '/home/sysek/rpm/BUILD/polybar-3.1.0/build'
make: *** [Makefile:24: install] Error
```

**Comment by patrick96** [comment]
@sysek And without the patch, you get the same error as the others? The errors you're getting seem to be unrelated to the issue described above. Please open a new issue with the information you already posted, as well as the name and versions of all packages with xcb in their name that you have installed.

**Comment by sysek** [comment]
@patrick96 without patch get the errors like in first post, so I think patch is working.

>Please open a new issue with the information you already posted, as well as the name and versions of all packages with xcb in their name that you have installed.

wow, you want me to open the new ticket? it's gonna be tricky, because I'm gonna to do that for first time haha.

**Comment by patrick96** [comment]
@sysek It's really not that difficult, you can do it [here](https://github.com/jaagr/polybar/issues/new), just post what you already posted and also the other information I requested.

**Comment by dinotheextinct** [comment]
I am still not sure how to solve the compiling issue described here?

**Comment by patrick96** [comment]
When compiling against the newest commit, you shouldn't have any problems

**Comment by dinotheextinct** [comment]
How do the install instructions change when trying to compile against the newest commit?

> git clone --branch 3.1.0 --recursive https://github.com/jaagr/polybar

Is this still correct?

**Comment by patrick96** [comment]
You have to remove `--branch 3.1.0` or if you already cloned it, do `git checkout master` inside the repo

**Comment by sysek** [comment]
@dinotheextinct the question is do you want install polybar official release (3.1.0) or install the edge version from git. Anyway instruction are still the same.

**Comment by dinotheextinct** [comment]
Wow thanks for the blazing responses, will try with removing branch.

@sysek Well in order to bypass this error I am forced to try the "edge" version.

**Comment by sysek** [comment]
@dinotheextinct as @patrick96 wite, just remove ```--branch 3.1.0``` :)
