### ISSUE TITLE
make userconfig doesn't work, maybe..

### ISSUE THREAD

**Issue by eVanilla** [jaagr/polybar#982]
```bash
$ make userconfig
make: *** No rule to make target 'userconfig'.  Stop.
```
what should i do now ?
```
$ polybar -vv
polybar 3.1.0-36-g5c7ff09

Features: +alsa +curl +i3 +mpd +network +pulseaudio

X extensions: +randr (-monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags:  -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: 
```
how do i create example config ?

**Comment by eVanilla** [comment]
also i got this error at the end of installation: 
```
Scanning dependencies of target userconfig
-- Installing: /home/evoke/.config/polybar/config
CMake Error at cmake/userconfig.cmake:7 (file):
  file INSTALL cannot copy file "/home/evoke/Desktop/polybar/doc/config" to
  "/home/evoke/.config/polybar/config".


CMakeFiles/userconfig.dir/build.make:57: recipe for target 'CMakeFiles/userconfig' failed
make[3]: *** [CMakeFiles/userconfig] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/userconfig.dir/all' failed
make[2]: *** [CMakeFiles/userconfig.dir/all] Error 2
CMakeFiles/Makefile2:106: recipe for target 'CMakeFiles/userconfig.dir/rule' failed
make[1]: *** [CMakeFiles/userconfig.dir/rule] Error 2
Makefile:175: recipe for target 'userconfig' failed
make: *** [userconfig] Error 2
** Failed to install user configuration...
```

**Comment by patrick96** [comment]
In which folder are you running `make userconfig`?

**Comment by eVanilla** [comment]
```polybar/build```
and got this output:
```
$ make userconfig
[  4%] Built target jsoncpp_lib_static
[  9%] Built target xpp
[ 12%] Built target i3ipc++
[100%] Built target polybar
-- Installing: /home/evoke/.config/polybar/config
CMake Error at cmake/userconfig.cmake:7 (file):
  file INSTALL cannot copy file "/home/evoke/Desktop/polybar/doc/config" to
  "/home/evoke/.config/polybar/config".


CMakeFiles/userconfig.dir/build.make:57: recipe for target 'CMakeFiles/userconfig' failed
make[3]: *** [CMakeFiles/userconfig] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/userconfig.dir/all' failed
make[2]: *** [CMakeFiles/userconfig.dir/all] Error 2
CMakeFiles/Makefile2:106: recipe for target 'CMakeFiles/userconfig.dir/rule' failed
make[1]: *** [CMakeFiles/userconfig.dir/rule] Error 2
Makefile:175: recipe for target 'userconfig' failed
make: *** [userconfig] Error 2
```

**Comment by patrick96** [comment]
This may be an issue with the permissions on your system. Make sure your user has write access to `~/.config/polybar/config`

**Comment by eVanilla** [comment]
ahaa.. fixed it by `sudo` command but i got another error:
```
$ polybar example
warn: No monitor specified, using "LVDS1"
error: Disabling module "bspwm" (reason: Could not find socket: /tmp/bspwm_0_0-socket)
error: Disabling module "i3" (reason: Could not find socket: <empty>)
error: module/mpd: Connection refused
error: Disabling module "volume" (reason: Missing parameter "module/volume.type")
error: Disabling module "battery" (reason: No suitable way to get current capacity value)
Segmentation fault (core dumped)
```

**Comment by patrick96** [comment]
That doesn't look good...
Can you run polybar inside gdb and post the stacktrace:
```bash
gdb -batch -nh -ex run -ex bt full --args polybar example
```

**Comment by eVanilla** [comment]
hmmm... yea it doesn't sounds good
```
$ gdb -batch -nh -ex run -ex bt full --args polybar example[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
[New Thread 0xb6485b40 (LWP 16971)]
warn: No monitor specified, using "LVDS1"
error: Disabling module "bspwm" (reason: Could not find socket: /tmp/bspwm_0_0-socket)
error: Disabling module "i3" (reason: Could not find socket: <empty>)
error: module/mpd: Connection refused
error: Disabling module "volume" (reason: Missing parameter "module/volume.type")
error: Disabling module "battery" (reason: No suitable way to get current capacity value)
[New Thread 0xb5c84b40 (LWP 16974)]
[New Thread 0xb52ffb40 (LWP 16975)]

Thread 3 "polybar" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb5c84b40 (LWP 16974)]
0x08127858 in polybar::v3_1_0_36_g5c7ff09::mpd::mpdstatus::match_state (this=0x0, state=polybar::v3_1_0_36_g5c7ff09::mpd::mpdstate::PLAYING) at /home/evoke/Desktop/polybar/src/adapters/mpd.cpp:419
419	    return state == m_state;
#0  0x08127858 in polybar::v3_1_0_36_g5c7ff09::mpd::mpdstatus::match_state (this=0x0, state=polybar::v3_1_0_36_g5c7ff09::mpd::mpdstate::PLAYING) at /home/evoke/Desktop/polybar/src/adapters/mpd.cpp:419
#1  0x0814c132 in polybar::v3_1_0_36_g5c7ff09::modules::mpd_module::update (this=0x832ae38) at /home/evoke/Desktop/polybar/src/modules/mpd.cpp:203
#2  0x08155f01 in polybar::v3_1_0_36_g5c7ff09::modules::event_module<polybar::v3_1_0_36_g5c7ff09::modules::mpd_module>::runner (this=0x832ae38) at /home/evoke/Desktop/polybar/include/modules/meta/event_module.hpp:23
#3  0xb7a2662e in ?? () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#4  0xb7900295 in start_thread (arg=0xb5c84b40) at pthread_create.c:333
#5  0xb782b0ae in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:114
```
